// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SCHEMA_CLICE_INDEX_BINARY_H_
#define FLATBUFFERS_GENERATED_SCHEMA_CLICE_INDEX_BINARY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR == 9 &&
                  FLATBUFFERS_VERSION_REVISION == 23,
              "Non-compatible flatbuffers version included");

namespace clice {
namespace index {
namespace binary {

struct Range;

struct Occurrence;

struct Relation;

struct CacheEntry;
struct CacheEntryBuilder;

struct IncludeContext;

struct HeaderContextEntry;
struct HeaderContextEntryBuilder;

struct IncludeLocation;

struct CompilationContextEntry;
struct CompilationContextEntryBuilder;

struct OccurrenceEntry;
struct OccurrenceEntryBuilder;

struct RelationEntry;
struct RelationEntryBuilder;

struct SymbolRelationsEntry;
struct SymbolRelationsEntryBuilder;

struct Symbol;
struct SymbolBuilder;

struct SymbolEntry;
struct SymbolEntryBuilder;

struct MergedIndex;
struct MergedIndexBuilder;

struct TUFileRelationsEntry;
struct TUFileRelationsEntryBuilder;

struct TUFileIndexEntry;
struct TUFileIndexEntryBuilder;

struct TUIndex;
struct TUIndexBuilder;

struct PathEntry;
struct PathEntryBuilder;

struct PathMapEntry;

struct ProjectIndex;
struct ProjectIndexBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Range FLATBUFFERS_FINAL_CLASS {
private:
    uint32_t begin_;
    uint32_t end_;

public:
    Range() : begin_(0), end_(0) {}
    Range(uint32_t _begin, uint32_t _end) :
        begin_(::flatbuffers::EndianScalar(_begin)), end_(::flatbuffers::EndianScalar(_end)) {}
    uint32_t begin() const {
        return ::flatbuffers::EndianScalar(begin_);
    }
    uint32_t end() const {
        return ::flatbuffers::EndianScalar(end_);
    }
};

FLATBUFFERS_STRUCT_END(Range, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Occurrence FLATBUFFERS_FINAL_CLASS {
private:
    clice::index::binary::Range range_;
    uint64_t target_;

public:
    Occurrence() : range_(), target_(0) {}
    Occurrence(const clice::index::binary::Range& _range, uint64_t _target) :
        range_(_range), target_(::flatbuffers::EndianScalar(_target)) {}
    const clice::index::binary::Range& range() const {
        return range_;
    }
    uint64_t target() const {
        return ::flatbuffers::EndianScalar(target_);
    }
};

FLATBUFFERS_STRUCT_END(Occurrence, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Relation FLATBUFFERS_FINAL_CLASS {
private:
    uint32_t kind_;
    uint32_t padding_;
    clice::index::binary::Range range_;
    uint64_t target_symbol_;

public:
    Relation() : kind_(0), padding_(0), range_(), target_symbol_(0) {}
    Relation(uint32_t _kind,
             uint32_t _padding,
             const clice::index::binary::Range& _range,
             uint64_t _target_symbol) :
        kind_(::flatbuffers::EndianScalar(_kind)), padding_(::flatbuffers::EndianScalar(_padding)),
        range_(_range), target_symbol_(::flatbuffers::EndianScalar(_target_symbol)) {}
    uint32_t kind() const {
        return ::flatbuffers::EndianScalar(kind_);
    }
    uint32_t padding() const {
        return ::flatbuffers::EndianScalar(padding_);
    }
    const clice::index::binary::Range& range() const {
        return range_;
    }
    uint64_t target_symbol() const {
        return ::flatbuffers::EndianScalar(target_symbol_);
    }
};

FLATBUFFERS_STRUCT_END(Relation, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) IncludeContext FLATBUFFERS_FINAL_CLASS {
private:
    uint32_t include_id_;
    uint32_t canonical_id_;

public:
    IncludeContext() : include_id_(0), canonical_id_(0) {}
    IncludeContext(uint32_t _include_id, uint32_t _canonical_id) :
        include_id_(::flatbuffers::EndianScalar(_include_id)),
        canonical_id_(::flatbuffers::EndianScalar(_canonical_id)) {}
    uint32_t include_id() const {
        return ::flatbuffers::EndianScalar(include_id_);
    }
    uint32_t canonical_id() const {
        return ::flatbuffers::EndianScalar(canonical_id_);
    }
};

FLATBUFFERS_STRUCT_END(IncludeContext, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) IncludeLocation FLATBUFFERS_FINAL_CLASS {
private:
    uint32_t path_id_;
    uint32_t line_;
    uint32_t include_id_;

public:
    IncludeLocation() : path_id_(0), line_(0), include_id_(0) {}
    IncludeLocation(uint32_t _path_id, uint32_t _line, uint32_t _include_id) :
        path_id_(::flatbuffers::EndianScalar(_path_id)), line_(::flatbuffers::EndianScalar(_line)),
        include_id_(::flatbuffers::EndianScalar(_include_id)) {}
    uint32_t path_id() const {
        return ::flatbuffers::EndianScalar(path_id_);
    }
    uint32_t line() const {
        return ::flatbuffers::EndianScalar(line_);
    }
    uint32_t include_id() const {
        return ::flatbuffers::EndianScalar(include_id_);
    }
};

FLATBUFFERS_STRUCT_END(IncludeLocation, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PathMapEntry FLATBUFFERS_FINAL_CLASS {
private:
    uint32_t source_;
    uint32_t index_;

public:
    PathMapEntry() : source_(0), index_(0) {}
    PathMapEntry(uint32_t _source, uint32_t _index) :
        source_(::flatbuffers::EndianScalar(_source)), index_(::flatbuffers::EndianScalar(_index)) {
    }
    uint32_t source() const {
        return ::flatbuffers::EndianScalar(source_);
    }
    uint32_t index() const {
        return ::flatbuffers::EndianScalar(index_);
    }
};

FLATBUFFERS_STRUCT_END(PathMapEntry, 8);

struct CacheEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef CacheEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SHA256 = 4,
        VT_CANONICAL_ID = 6
    };

    const ::flatbuffers::String* sha256() const {
        return GetPointer<const ::flatbuffers::String*>(VT_SHA256);
    }

    uint32_t canonical_id() const {
        return GetField<uint32_t>(VT_CANONICAL_ID, 0);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_SHA256) &&
               verifier.VerifyString(sha256()) &&
               VerifyField<uint32_t>(verifier, VT_CANONICAL_ID, 4) && verifier.EndTable();
    }
};

struct CacheEntryBuilder {
    typedef CacheEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_sha256(::flatbuffers::Offset<::flatbuffers::String> sha256) {
        fbb_.AddOffset(CacheEntry::VT_SHA256, sha256);
    }

    void add_canonical_id(uint32_t canonical_id) {
        fbb_.AddElement<uint32_t>(CacheEntry::VT_CANONICAL_ID, canonical_id, 0);
    }

    explicit CacheEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<CacheEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<CacheEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<CacheEntry>
    CreateCacheEntry(::flatbuffers::FlatBufferBuilder& _fbb,
                     ::flatbuffers::Offset<::flatbuffers::String> sha256 = 0,
                     uint32_t canonical_id = 0) {
    CacheEntryBuilder builder_(_fbb);
    builder_.add_canonical_id(canonical_id);
    builder_.add_sha256(sha256);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<CacheEntry>
    CreateCacheEntryDirect(::flatbuffers::FlatBufferBuilder& _fbb,
                           const char* sha256 = nullptr,
                           uint32_t canonical_id = 0) {
    auto sha256__ = sha256 ? _fbb.CreateString(sha256) : 0;
    return clice::index::binary::CreateCacheEntry(_fbb, sha256__, canonical_id);
}

struct HeaderContextEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef HeaderContextEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_PATH_ID = 4,
        VT_VERSION = 6,
        VT_INCLUDES = 8
    };

    uint32_t path_id() const {
        return GetField<uint32_t>(VT_PATH_ID, 0);
    }

    uint32_t version() const {
        return GetField<uint32_t>(VT_VERSION, 0);
    }

    const ::flatbuffers::Vector<const clice::index::binary::IncludeContext*>* includes() const {
        return GetPointer<
            const ::flatbuffers::Vector<const clice::index::binary::IncludeContext*>*>(VT_INCLUDES);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint32_t>(verifier, VT_PATH_ID, 4) &&
               VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
               VerifyOffset(verifier, VT_INCLUDES) && verifier.VerifyVector(includes()) &&
               verifier.EndTable();
    }
};

struct HeaderContextEntryBuilder {
    typedef HeaderContextEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_path_id(uint32_t path_id) {
        fbb_.AddElement<uint32_t>(HeaderContextEntry::VT_PATH_ID, path_id, 0);
    }

    void add_version(uint32_t version) {
        fbb_.AddElement<uint32_t>(HeaderContextEntry::VT_VERSION, version, 0);
    }

    void add_includes(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeContext*>>
            includes) {
        fbb_.AddOffset(HeaderContextEntry::VT_INCLUDES, includes);
    }

    explicit HeaderContextEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<HeaderContextEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<HeaderContextEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<HeaderContextEntry> CreateHeaderContextEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t path_id = 0,
    uint32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeContext*>>
        includes = 0) {
    HeaderContextEntryBuilder builder_(_fbb);
    builder_.add_includes(includes);
    builder_.add_version(version);
    builder_.add_path_id(path_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<HeaderContextEntry> CreateHeaderContextEntryDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t path_id = 0,
    uint32_t version = 0,
    const std::vector<clice::index::binary::IncludeContext>* includes = nullptr) {
    auto includes__ =
        includes ? _fbb.CreateVectorOfStructs<clice::index::binary::IncludeContext>(*includes) : 0;
    return clice::index::binary::CreateHeaderContextEntry(_fbb, path_id, version, includes__);
}

struct CompilationContextEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef CompilationContextEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_PATH_ID = 4,
        VT_VERSION = 6,
        VT_CANONICAL_ID = 8,
        VT_BUILD_AT = 10,
        VT_INCLUDE_LOCATIONS = 12
    };

    uint32_t path_id() const {
        return GetField<uint32_t>(VT_PATH_ID, 0);
    }

    uint32_t version() const {
        return GetField<uint32_t>(VT_VERSION, 0);
    }

    uint32_t canonical_id() const {
        return GetField<uint32_t>(VT_CANONICAL_ID, 0);
    }

    uint64_t build_at() const {
        return GetField<uint64_t>(VT_BUILD_AT, 0);
    }

    const ::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>*
        include_locations() const {
        return GetPointer<
            const ::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>*>(
            VT_INCLUDE_LOCATIONS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint32_t>(verifier, VT_PATH_ID, 4) &&
               VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
               VerifyField<uint32_t>(verifier, VT_CANONICAL_ID, 4) &&
               VerifyField<uint64_t>(verifier, VT_BUILD_AT, 8) &&
               VerifyOffset(verifier, VT_INCLUDE_LOCATIONS) &&
               verifier.VerifyVector(include_locations()) && verifier.EndTable();
    }
};

struct CompilationContextEntryBuilder {
    typedef CompilationContextEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_path_id(uint32_t path_id) {
        fbb_.AddElement<uint32_t>(CompilationContextEntry::VT_PATH_ID, path_id, 0);
    }

    void add_version(uint32_t version) {
        fbb_.AddElement<uint32_t>(CompilationContextEntry::VT_VERSION, version, 0);
    }

    void add_canonical_id(uint32_t canonical_id) {
        fbb_.AddElement<uint32_t>(CompilationContextEntry::VT_CANONICAL_ID, canonical_id, 0);
    }

    void add_build_at(uint64_t build_at) {
        fbb_.AddElement<uint64_t>(CompilationContextEntry::VT_BUILD_AT, build_at, 0);
    }

    void add_include_locations(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>>
            include_locations) {
        fbb_.AddOffset(CompilationContextEntry::VT_INCLUDE_LOCATIONS, include_locations);
    }

    explicit CompilationContextEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<CompilationContextEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<CompilationContextEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<CompilationContextEntry> CreateCompilationContextEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t path_id = 0,
    uint32_t version = 0,
    uint32_t canonical_id = 0,
    uint64_t build_at = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>>
        include_locations = 0) {
    CompilationContextEntryBuilder builder_(_fbb);
    builder_.add_build_at(build_at);
    builder_.add_include_locations(include_locations);
    builder_.add_canonical_id(canonical_id);
    builder_.add_version(version);
    builder_.add_path_id(path_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<CompilationContextEntry> CreateCompilationContextEntryDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t path_id = 0,
    uint32_t version = 0,
    uint32_t canonical_id = 0,
    uint64_t build_at = 0,
    const std::vector<clice::index::binary::IncludeLocation>* include_locations = nullptr) {
    auto include_locations__ =
        include_locations
            ? _fbb.CreateVectorOfStructs<clice::index::binary::IncludeLocation>(*include_locations)
            : 0;
    return clice::index::binary::CreateCompilationContextEntry(_fbb,
                                                               path_id,
                                                               version,
                                                               canonical_id,
                                                               build_at,
                                                               include_locations__);
}

struct OccurrenceEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef OccurrenceEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_OCCURRENCE = 4,
        VT_CONTEXT = 6
    };

    const clice::index::binary::Occurrence* occurrence() const {
        return GetStruct<const clice::index::binary::Occurrence*>(VT_OCCURRENCE);
    }

    const ::flatbuffers::Vector<uint8_t>* context() const {
        return GetPointer<const ::flatbuffers::Vector<uint8_t>*>(VT_CONTEXT);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<clice::index::binary::Occurrence>(verifier, VT_OCCURRENCE, 8) &&
               VerifyOffset(verifier, VT_CONTEXT) && verifier.VerifyVector(context()) &&
               verifier.EndTable();
    }
};

struct OccurrenceEntryBuilder {
    typedef OccurrenceEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_occurrence(const clice::index::binary::Occurrence* occurrence) {
        fbb_.AddStruct(OccurrenceEntry::VT_OCCURRENCE, occurrence);
    }

    void add_context(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> context) {
        fbb_.AddOffset(OccurrenceEntry::VT_CONTEXT, context);
    }

    explicit OccurrenceEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<OccurrenceEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<OccurrenceEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<OccurrenceEntry>
    CreateOccurrenceEntry(::flatbuffers::FlatBufferBuilder& _fbb,
                          const clice::index::binary::Occurrence* occurrence = nullptr,
                          ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> context = 0) {
    OccurrenceEntryBuilder builder_(_fbb);
    builder_.add_context(context);
    builder_.add_occurrence(occurrence);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<OccurrenceEntry>
    CreateOccurrenceEntryDirect(::flatbuffers::FlatBufferBuilder& _fbb,
                                const clice::index::binary::Occurrence* occurrence = nullptr,
                                const std::vector<uint8_t>* context = nullptr) {
    auto context__ = context ? _fbb.CreateVector<uint8_t>(*context) : 0;
    return clice::index::binary::CreateOccurrenceEntry(_fbb, occurrence, context__);
}

struct RelationEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef RelationEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_RELATION = 4,
        VT_CONTEXT = 6
    };

    const clice::index::binary::Relation* relation() const {
        return GetStruct<const clice::index::binary::Relation*>(VT_RELATION);
    }

    const ::flatbuffers::Vector<uint8_t>* context() const {
        return GetPointer<const ::flatbuffers::Vector<uint8_t>*>(VT_CONTEXT);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<clice::index::binary::Relation>(verifier, VT_RELATION, 8) &&
               VerifyOffset(verifier, VT_CONTEXT) && verifier.VerifyVector(context()) &&
               verifier.EndTable();
    }
};

struct RelationEntryBuilder {
    typedef RelationEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_relation(const clice::index::binary::Relation* relation) {
        fbb_.AddStruct(RelationEntry::VT_RELATION, relation);
    }

    void add_context(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> context) {
        fbb_.AddOffset(RelationEntry::VT_CONTEXT, context);
    }

    explicit RelationEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<RelationEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<RelationEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<RelationEntry>
    CreateRelationEntry(::flatbuffers::FlatBufferBuilder& _fbb,
                        const clice::index::binary::Relation* relation = nullptr,
                        ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> context = 0) {
    RelationEntryBuilder builder_(_fbb);
    builder_.add_context(context);
    builder_.add_relation(relation);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<RelationEntry>
    CreateRelationEntryDirect(::flatbuffers::FlatBufferBuilder& _fbb,
                              const clice::index::binary::Relation* relation = nullptr,
                              const std::vector<uint8_t>* context = nullptr) {
    auto context__ = context ? _fbb.CreateVector<uint8_t>(*context) : 0;
    return clice::index::binary::CreateRelationEntry(_fbb, relation, context__);
}

struct SymbolRelationsEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef SymbolRelationsEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SYMBOL = 4,
        VT_RELATIONS = 6
    };

    uint64_t symbol() const {
        return GetField<uint64_t>(VT_SYMBOL, 0);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::RelationEntry>>*
        relations() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::RelationEntry>>*>(VT_RELATIONS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_SYMBOL, 8) &&
               VerifyOffset(verifier, VT_RELATIONS) && verifier.VerifyVector(relations()) &&
               verifier.VerifyVectorOfTables(relations()) && verifier.EndTable();
    }
};

struct SymbolRelationsEntryBuilder {
    typedef SymbolRelationsEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_symbol(uint64_t symbol) {
        fbb_.AddElement<uint64_t>(SymbolRelationsEntry::VT_SYMBOL, symbol, 0);
    }

    void add_relations(::flatbuffers::Offset<::flatbuffers::Vector<
                           ::flatbuffers::Offset<clice::index::binary::RelationEntry>>> relations) {
        fbb_.AddOffset(SymbolRelationsEntry::VT_RELATIONS, relations);
    }

    explicit SymbolRelationsEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<SymbolRelationsEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<SymbolRelationsEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<SymbolRelationsEntry> CreateSymbolRelationsEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t symbol = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::RelationEntry>>> relations = 0) {
    SymbolRelationsEntryBuilder builder_(_fbb);
    builder_.add_symbol(symbol);
    builder_.add_relations(relations);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<SymbolRelationsEntry> CreateSymbolRelationsEntryDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t symbol = 0,
    const std::vector<::flatbuffers::Offset<clice::index::binary::RelationEntry>>* relations =
        nullptr) {
    auto relations__ =
        relations ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::RelationEntry>>(
                        *relations)
                  : 0;
    return clice::index::binary::CreateSymbolRelationsEntry(_fbb, symbol, relations__);
}

struct Symbol FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef SymbolBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_NAME = 4,
        VT_KIND = 6,
        VT_REFS = 8
    };

    const ::flatbuffers::String* name() const {
        return GetPointer<const ::flatbuffers::String*>(VT_NAME);
    }

    uint8_t kind() const {
        return GetField<uint8_t>(VT_KIND, 0);
    }

    const ::flatbuffers::Vector<uint8_t>* refs() const {
        return GetPointer<const ::flatbuffers::Vector<uint8_t>*>(VT_REFS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_NAME) &&
               verifier.VerifyString(name()) && VerifyField<uint8_t>(verifier, VT_KIND, 1) &&
               VerifyOffset(verifier, VT_REFS) && verifier.VerifyVector(refs()) &&
               verifier.EndTable();
    }
};

struct SymbolBuilder {
    typedef Symbol Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
        fbb_.AddOffset(Symbol::VT_NAME, name);
    }

    void add_kind(uint8_t kind) {
        fbb_.AddElement<uint8_t>(Symbol::VT_KIND, kind, 0);
    }

    void add_refs(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> refs) {
        fbb_.AddOffset(Symbol::VT_REFS, refs);
    }

    explicit SymbolBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<Symbol> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Symbol>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Symbol>
    CreateSymbol(::flatbuffers::FlatBufferBuilder& _fbb,
                 ::flatbuffers::Offset<::flatbuffers::String> name = 0,
                 uint8_t kind = 0,
                 ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> refs = 0) {
    SymbolBuilder builder_(_fbb);
    builder_.add_refs(refs);
    builder_.add_name(name);
    builder_.add_kind(kind);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Symbol>
    CreateSymbolDirect(::flatbuffers::FlatBufferBuilder& _fbb,
                       const char* name = nullptr,
                       uint8_t kind = 0,
                       const std::vector<uint8_t>* refs = nullptr) {
    auto name__ = name ? _fbb.CreateString(name) : 0;
    auto refs__ = refs ? _fbb.CreateVector<uint8_t>(*refs) : 0;
    return clice::index::binary::CreateSymbol(_fbb, name__, kind, refs__);
}

struct SymbolEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef SymbolEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SYMBOL_ID = 4,
        VT_SYMBOL = 6
    };

    uint64_t symbol_id() const {
        return GetField<uint64_t>(VT_SYMBOL_ID, 0);
    }

    const clice::index::binary::Symbol* symbol() const {
        return GetPointer<const clice::index::binary::Symbol*>(VT_SYMBOL);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_SYMBOL_ID, 8) &&
               VerifyOffset(verifier, VT_SYMBOL) && verifier.VerifyTable(symbol()) &&
               verifier.EndTable();
    }
};

struct SymbolEntryBuilder {
    typedef SymbolEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_symbol_id(uint64_t symbol_id) {
        fbb_.AddElement<uint64_t>(SymbolEntry::VT_SYMBOL_ID, symbol_id, 0);
    }

    void add_symbol(::flatbuffers::Offset<clice::index::binary::Symbol> symbol) {
        fbb_.AddOffset(SymbolEntry::VT_SYMBOL, symbol);
    }

    explicit SymbolEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<SymbolEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<SymbolEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<SymbolEntry>
    CreateSymbolEntry(::flatbuffers::FlatBufferBuilder& _fbb,
                      uint64_t symbol_id = 0,
                      ::flatbuffers::Offset<clice::index::binary::Symbol> symbol = 0) {
    SymbolEntryBuilder builder_(_fbb);
    builder_.add_symbol_id(symbol_id);
    builder_.add_symbol(symbol);
    return builder_.Finish();
}

struct MergedIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef MergedIndexBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_MAX_CANONICAL_ID = 4,
        VT_CANONICAL_CACHE = 6,
        VT_HEADER_CONTEXTS = 8,
        VT_COMPILATION_CONTEXTS = 10,
        VT_OCCURRENCES = 12,
        VT_RELATIONS = 14,
        VT_REMOVED = 16,
        VT_CONTENT = 18,
        VT_LINE_STARTS = 20
    };

    uint32_t max_canonical_id() const {
        return GetField<uint32_t>(VT_MAX_CANONICAL_ID, 0);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::CacheEntry>>*
        canonical_cache() const {
        return GetPointer<
            const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::CacheEntry>>*>(
            VT_CANONICAL_CACHE);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>*
        header_contexts() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>*>(VT_HEADER_CONTEXTS);
    }

    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>*
        compilation_contexts() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>*>(
            VT_COMPILATION_CONTEXTS);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>*
        occurrences() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>*>(VT_OCCURRENCES);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>*
        relations() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>*>(VT_RELATIONS);
    }

    const ::flatbuffers::Vector<uint8_t>* removed() const {
        return GetPointer<const ::flatbuffers::Vector<uint8_t>*>(VT_REMOVED);
    }

    const ::flatbuffers::String* content() const {
        return GetPointer<const ::flatbuffers::String*>(VT_CONTENT);
    }

    const ::flatbuffers::Vector<uint32_t>* line_starts() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t>*>(VT_LINE_STARTS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_MAX_CANONICAL_ID, 4) &&
               VerifyOffset(verifier, VT_CANONICAL_CACHE) &&
               verifier.VerifyVector(canonical_cache()) &&
               verifier.VerifyVectorOfTables(canonical_cache()) &&
               VerifyOffset(verifier, VT_HEADER_CONTEXTS) &&
               verifier.VerifyVector(header_contexts()) &&
               verifier.VerifyVectorOfTables(header_contexts()) &&
               VerifyOffset(verifier, VT_COMPILATION_CONTEXTS) &&
               verifier.VerifyVector(compilation_contexts()) &&
               verifier.VerifyVectorOfTables(compilation_contexts()) &&
               VerifyOffset(verifier, VT_OCCURRENCES) && verifier.VerifyVector(occurrences()) &&
               verifier.VerifyVectorOfTables(occurrences()) &&
               VerifyOffset(verifier, VT_RELATIONS) && verifier.VerifyVector(relations()) &&
               verifier.VerifyVectorOfTables(relations()) && VerifyOffset(verifier, VT_REMOVED) &&
               verifier.VerifyVector(removed()) && VerifyOffset(verifier, VT_CONTENT) &&
               verifier.VerifyString(content()) && VerifyOffset(verifier, VT_LINE_STARTS) &&
               verifier.VerifyVector(line_starts()) && verifier.EndTable();
    }
};

struct MergedIndexBuilder {
    typedef MergedIndex Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_max_canonical_id(uint32_t max_canonical_id) {
        fbb_.AddElement<uint32_t>(MergedIndex::VT_MAX_CANONICAL_ID, max_canonical_id, 0);
    }

    void add_canonical_cache(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::CacheEntry>>>
            canonical_cache) {
        fbb_.AddOffset(MergedIndex::VT_CANONICAL_CACHE, canonical_cache);
    }

    void add_header_contexts(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>>
            header_contexts) {
        fbb_.AddOffset(MergedIndex::VT_HEADER_CONTEXTS, header_contexts);
    }

    void add_compilation_contexts(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>>
            compilation_contexts) {
        fbb_.AddOffset(MergedIndex::VT_COMPILATION_CONTEXTS, compilation_contexts);
    }

    void add_occurrences(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>>
            occurrences) {
        fbb_.AddOffset(MergedIndex::VT_OCCURRENCES, occurrences);
    }

    void add_relations(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>> relations) {
        fbb_.AddOffset(MergedIndex::VT_RELATIONS, relations);
    }

    void add_removed(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> removed) {
        fbb_.AddOffset(MergedIndex::VT_REMOVED, removed);
    }

    void add_content(::flatbuffers::Offset<::flatbuffers::String> content) {
        fbb_.AddOffset(MergedIndex::VT_CONTENT, content);
    }

    void add_line_starts(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> line_starts) {
        fbb_.AddOffset(MergedIndex::VT_LINE_STARTS, line_starts);
    }

    explicit MergedIndexBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<MergedIndex> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<MergedIndex>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<MergedIndex> CreateMergedIndex(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t max_canonical_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::CacheEntry>>> canonical_cache = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>> header_contexts = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>>
        compilation_contexts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>> occurrences = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>> relations = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> removed = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> line_starts = 0) {
    MergedIndexBuilder builder_(_fbb);
    builder_.add_line_starts(line_starts);
    builder_.add_content(content);
    builder_.add_removed(removed);
    builder_.add_relations(relations);
    builder_.add_occurrences(occurrences);
    builder_.add_compilation_contexts(compilation_contexts);
    builder_.add_header_contexts(header_contexts);
    builder_.add_canonical_cache(canonical_cache);
    builder_.add_max_canonical_id(max_canonical_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<MergedIndex> CreateMergedIndexDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t max_canonical_id = 0,
    const std::vector<::flatbuffers::Offset<clice::index::binary::CacheEntry>>* canonical_cache =
        nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>*
        header_contexts = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>*
        compilation_contexts = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>* occurrences =
        nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>*
        relations = nullptr,
    const std::vector<uint8_t>* removed = nullptr,
    const char* content = nullptr,
    const std::vector<uint32_t>* line_starts = nullptr) {
    auto canonical_cache__ =
        canonical_cache
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::CacheEntry>>(
                  *canonical_cache)
            : 0;
    auto header_contexts__ =
        header_contexts
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::HeaderContextEntry>>(
                  *header_contexts)
            : 0;
    auto compilation_contexts__ =
        compilation_contexts
            ? _fbb.CreateVector<
                  ::flatbuffers::Offset<clice::index::binary::CompilationContextEntry>>(
                  *compilation_contexts)
            : 0;
    auto occurrences__ =
        occurrences
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::OccurrenceEntry>>(
                  *occurrences)
            : 0;
    auto relations__ =
        relations
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::SymbolRelationsEntry>>(
                  *relations)
            : 0;
    auto removed__ = removed ? _fbb.CreateVector<uint8_t>(*removed) : 0;
    auto content__ = content ? _fbb.CreateString(content) : 0;
    auto line_starts__ = line_starts ? _fbb.CreateVector<uint32_t>(*line_starts) : 0;
    return clice::index::binary::CreateMergedIndex(_fbb,
                                                   max_canonical_id,
                                                   canonical_cache__,
                                                   header_contexts__,
                                                   compilation_contexts__,
                                                   occurrences__,
                                                   relations__,
                                                   removed__,
                                                   content__,
                                                   line_starts__);
}

struct TUFileRelationsEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef TUFileRelationsEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SYMBOL = 4,
        VT_RELATIONS = 6
    };

    uint64_t symbol() const {
        return GetField<uint64_t>(VT_SYMBOL, 0);
    }

    const ::flatbuffers::Vector<const clice::index::binary::Relation*>* relations() const {
        return GetPointer<const ::flatbuffers::Vector<const clice::index::binary::Relation*>*>(
            VT_RELATIONS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_SYMBOL, 8) &&
               VerifyOffset(verifier, VT_RELATIONS) && verifier.VerifyVector(relations()) &&
               verifier.EndTable();
    }
};

struct TUFileRelationsEntryBuilder {
    typedef TUFileRelationsEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_symbol(uint64_t symbol) {
        fbb_.AddElement<uint64_t>(TUFileRelationsEntry::VT_SYMBOL, symbol, 0);
    }

    void add_relations(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::Relation*>>
            relations) {
        fbb_.AddOffset(TUFileRelationsEntry::VT_RELATIONS, relations);
    }

    explicit TUFileRelationsEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<TUFileRelationsEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<TUFileRelationsEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<TUFileRelationsEntry> CreateTUFileRelationsEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t symbol = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::Relation*>> relations =
        0) {
    TUFileRelationsEntryBuilder builder_(_fbb);
    builder_.add_symbol(symbol);
    builder_.add_relations(relations);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<TUFileRelationsEntry> CreateTUFileRelationsEntryDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t symbol = 0,
    const std::vector<clice::index::binary::Relation>* relations = nullptr) {
    auto relations__ =
        relations ? _fbb.CreateVectorOfStructs<clice::index::binary::Relation>(*relations) : 0;
    return clice::index::binary::CreateTUFileRelationsEntry(_fbb, symbol, relations__);
}

struct TUFileIndexEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef TUFileIndexEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_FILE_ID = 4,
        VT_OCCURRENCES = 6,
        VT_RELATIONS = 8
    };

    uint32_t file_id() const {
        return GetField<uint32_t>(VT_FILE_ID, 0);
    }

    const ::flatbuffers::Vector<const clice::index::binary::Occurrence*>* occurrences() const {
        return GetPointer<const ::flatbuffers::Vector<const clice::index::binary::Occurrence*>*>(
            VT_OCCURRENCES);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>*
        relations() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>*>(VT_RELATIONS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint32_t>(verifier, VT_FILE_ID, 4) &&
               VerifyOffset(verifier, VT_OCCURRENCES) && verifier.VerifyVector(occurrences()) &&
               VerifyOffset(verifier, VT_RELATIONS) && verifier.VerifyVector(relations()) &&
               verifier.VerifyVectorOfTables(relations()) && verifier.EndTable();
    }
};

struct TUFileIndexEntryBuilder {
    typedef TUFileIndexEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_file_id(uint32_t file_id) {
        fbb_.AddElement<uint32_t>(TUFileIndexEntry::VT_FILE_ID, file_id, 0);
    }

    void add_occurrences(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::Occurrence*>>
            occurrences) {
        fbb_.AddOffset(TUFileIndexEntry::VT_OCCURRENCES, occurrences);
    }

    void add_relations(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>> relations) {
        fbb_.AddOffset(TUFileIndexEntry::VT_RELATIONS, relations);
    }

    explicit TUFileIndexEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<TUFileIndexEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<TUFileIndexEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<TUFileIndexEntry> CreateTUFileIndexEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t file_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::Occurrence*>>
        occurrences = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>> relations = 0) {
    TUFileIndexEntryBuilder builder_(_fbb);
    builder_.add_relations(relations);
    builder_.add_occurrences(occurrences);
    builder_.add_file_id(file_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<TUFileIndexEntry> CreateTUFileIndexEntryDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint32_t file_id = 0,
    const std::vector<clice::index::binary::Occurrence>* occurrences = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>*
        relations = nullptr) {
    auto occurrences__ =
        occurrences ? _fbb.CreateVectorOfStructs<clice::index::binary::Occurrence>(*occurrences)
                    : 0;
    auto relations__ =
        relations
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::TUFileRelationsEntry>>(
                  *relations)
            : 0;
    return clice::index::binary::CreateTUFileIndexEntry(_fbb, file_id, occurrences__, relations__);
}

struct TUIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef TUIndexBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_BUILT_AT = 4,
        VT_PATHS = 6,
        VT_LOCATIONS = 8,
        VT_SYMBOLS = 10,
        VT_FILE_INDICES = 12,
        VT_MAIN_FILE_INDEX = 14
    };

    uint64_t built_at() const {
        return GetField<uint64_t>(VT_BUILT_AT, 0);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>* paths() const {
        return GetPointer<
            const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>*>(VT_PATHS);
    }

    const ::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>* locations() const {
        return GetPointer<
            const ::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>*>(
            VT_LOCATIONS);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>*
        symbols() const {
        return GetPointer<
            const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>*>(
            VT_SYMBOLS);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>*
        file_indices() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>*>(VT_FILE_INDICES);
    }

    const clice::index::binary::TUFileIndexEntry* main_file_index() const {
        return GetPointer<const clice::index::binary::TUFileIndexEntry*>(VT_MAIN_FILE_INDEX);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_BUILT_AT, 8) &&
               VerifyOffset(verifier, VT_PATHS) && verifier.VerifyVector(paths()) &&
               verifier.VerifyVectorOfStrings(paths()) && VerifyOffset(verifier, VT_LOCATIONS) &&
               verifier.VerifyVector(locations()) && VerifyOffset(verifier, VT_SYMBOLS) &&
               verifier.VerifyVector(symbols()) && verifier.VerifyVectorOfTables(symbols()) &&
               VerifyOffset(verifier, VT_FILE_INDICES) && verifier.VerifyVector(file_indices()) &&
               verifier.VerifyVectorOfTables(file_indices()) &&
               VerifyOffset(verifier, VT_MAIN_FILE_INDEX) &&
               verifier.VerifyTable(main_file_index()) && verifier.EndTable();
    }
};

struct TUIndexBuilder {
    typedef TUIndex Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_built_at(uint64_t built_at) {
        fbb_.AddElement<uint64_t>(TUIndex::VT_BUILT_AT, built_at, 0);
    }

    void add_paths(
        ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>>
            paths) {
        fbb_.AddOffset(TUIndex::VT_PATHS, paths);
    }

    void add_locations(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>>
            locations) {
        fbb_.AddOffset(TUIndex::VT_LOCATIONS, locations);
    }

    void add_symbols(::flatbuffers::Offset<::flatbuffers::Vector<
                         ::flatbuffers::Offset<clice::index::binary::SymbolEntry>>> symbols) {
        fbb_.AddOffset(TUIndex::VT_SYMBOLS, symbols);
    }

    void add_file_indices(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>>
            file_indices) {
        fbb_.AddOffset(TUIndex::VT_FILE_INDICES, file_indices);
    }

    void add_main_file_index(
        ::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry> main_file_index) {
        fbb_.AddOffset(TUIndex::VT_MAIN_FILE_INDEX, main_file_index);
    }

    explicit TUIndexBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<TUIndex> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<TUIndex>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<TUIndex> CreateTUIndex(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t built_at = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>>
        paths = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::IncludeLocation*>>
        locations = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>> symbols =
        0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>> file_indices = 0,
    ::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry> main_file_index = 0) {
    TUIndexBuilder builder_(_fbb);
    builder_.add_built_at(built_at);
    builder_.add_main_file_index(main_file_index);
    builder_.add_file_indices(file_indices);
    builder_.add_symbols(symbols);
    builder_.add_locations(locations);
    builder_.add_paths(paths);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<TUIndex> CreateTUIndexDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    uint64_t built_at = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>>* paths = nullptr,
    const std::vector<clice::index::binary::IncludeLocation>* locations = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>* symbols = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>* file_indices =
        nullptr,
    ::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry> main_file_index = 0) {
    auto paths__ =
        paths ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*paths) : 0;
    auto locations__ =
        locations ? _fbb.CreateVectorOfStructs<clice::index::binary::IncludeLocation>(*locations)
                  : 0;
    auto symbols__ =
        symbols
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>(*symbols)
            : 0;
    auto file_indices__ =
        file_indices
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::TUFileIndexEntry>>(
                  *file_indices)
            : 0;
    return clice::index::binary::CreateTUIndex(_fbb,
                                               built_at,
                                               paths__,
                                               locations__,
                                               symbols__,
                                               file_indices__,
                                               main_file_index);
}

struct PathEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef PathEntryBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE { VT_PATH = 4, VT_ID = 6 };

    const ::flatbuffers::String* path() const {
        return GetPointer<const ::flatbuffers::String*>(VT_PATH);
    }

    uint32_t id() const {
        return GetField<uint32_t>(VT_ID, 0);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_PATH) &&
               verifier.VerifyString(path()) && VerifyField<uint32_t>(verifier, VT_ID, 4) &&
               verifier.EndTable();
    }
};

struct PathEntryBuilder {
    typedef PathEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
        fbb_.AddOffset(PathEntry::VT_PATH, path);
    }

    void add_id(uint32_t id) {
        fbb_.AddElement<uint32_t>(PathEntry::VT_ID, id, 0);
    }

    explicit PathEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<PathEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<PathEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<PathEntry>
    CreatePathEntry(::flatbuffers::FlatBufferBuilder& _fbb,
                    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
                    uint32_t id = 0) {
    PathEntryBuilder builder_(_fbb);
    builder_.add_id(id);
    builder_.add_path(path);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<PathEntry>
    CreatePathEntryDirect(::flatbuffers::FlatBufferBuilder& _fbb,
                          const char* path = nullptr,
                          uint32_t id = 0) {
    auto path__ = path ? _fbb.CreateString(path) : 0;
    return clice::index::binary::CreatePathEntry(_fbb, path__, id);
}

struct ProjectIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef ProjectIndexBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_PATHS = 4,
        VT_INDICES = 6,
        VT_SYMBOLS = 8
    };

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::PathEntry>>*
        paths() const {
        return GetPointer<
            const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::PathEntry>>*>(
            VT_PATHS);
    }

    const ::flatbuffers::Vector<const clice::index::binary::PathMapEntry*>* indices() const {
        return GetPointer<const ::flatbuffers::Vector<const clice::index::binary::PathMapEntry*>*>(
            VT_INDICES);
    }

    const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>*
        symbols() const {
        return GetPointer<
            const ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>*>(
            VT_SYMBOLS);
    }

    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_PATHS) &&
               verifier.VerifyVector(paths()) && verifier.VerifyVectorOfTables(paths()) &&
               VerifyOffset(verifier, VT_INDICES) && verifier.VerifyVector(indices()) &&
               VerifyOffset(verifier, VT_SYMBOLS) && verifier.VerifyVector(symbols()) &&
               verifier.VerifyVectorOfTables(symbols()) && verifier.EndTable();
    }
};

struct ProjectIndexBuilder {
    typedef ProjectIndex Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;

    void add_paths(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::PathEntry>>> paths) {
        fbb_.AddOffset(ProjectIndex::VT_PATHS, paths);
    }

    void add_indices(
        ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::PathMapEntry*>>
            indices) {
        fbb_.AddOffset(ProjectIndex::VT_INDICES, indices);
    }

    void add_symbols(::flatbuffers::Offset<::flatbuffers::Vector<
                         ::flatbuffers::Offset<clice::index::binary::SymbolEntry>>> symbols) {
        fbb_.AddOffset(ProjectIndex::VT_SYMBOLS, symbols);
    }

    explicit ProjectIndexBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }

    ::flatbuffers::Offset<ProjectIndex> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<ProjectIndex>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<ProjectIndex> CreateProjectIndex(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::PathEntry>>> paths = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const clice::index::binary::PathMapEntry*>>
        indices = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>> symbols =
        0) {
    ProjectIndexBuilder builder_(_fbb);
    builder_.add_symbols(symbols);
    builder_.add_indices(indices);
    builder_.add_paths(paths);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<ProjectIndex> CreateProjectIndexDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<clice::index::binary::PathEntry>>* paths = nullptr,
    const std::vector<clice::index::binary::PathMapEntry>* indices = nullptr,
    const std::vector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>* symbols =
        nullptr) {
    auto paths__ =
        paths ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::PathEntry>>(*paths)
              : 0;
    auto indices__ =
        indices ? _fbb.CreateVectorOfStructs<clice::index::binary::PathMapEntry>(*indices) : 0;
    auto symbols__ =
        symbols
            ? _fbb.CreateVector<::flatbuffers::Offset<clice::index::binary::SymbolEntry>>(*symbols)
            : 0;
    return clice::index::binary::CreateProjectIndex(_fbb, paths__, indices__, symbols__);
}

}  // namespace binary
}  // namespace index
}  // namespace clice

#endif  // FLATBUFFERS_GENERATED_SCHEMA_CLICE_INDEX_BINARY_H_
