#pragma once
#define CLANG_TIDY_ENABLE_STATIC_ANALYZER 0
#define CLANG_TIDY_ENABLE_QUERY_BASED_CUSTOM_CHECKS 0
#define LLVM_DEFAULT_TARGET_TRIPLE "aarch64-w64-mingw32"
# define LLVM_BUILTIN_TRAP __builtin_trap()
#define MDB_NOSUBDIR	0x4000
#define MDB_RDONLY		0x20000
#define MDB_NOTLS		0x200000
#define MDB_NOTFOUND	(-30798)
#define MDB_PAGE_NOTFOUND	(-30797)
#define MDB_CORRUPTED	(-30796)
#define MDB_VERSION_MISMATCH	(-30794)
#define MDB_INVALID	(-30793)
#define MDB_MAP_FULL	(-30792)
#define MDB_MAP_RESIZED	(-30785)
#define KOTATSU_CONCAT_IMPL(a, b) a##b
#define KOTATSU_CONCAT(a, b) KOTATSU_CONCAT_IMPL(a, b)
#define KOTATSU_ANNOTATION(name, ...)                                                                  struct name {                                                                                          constexpr static auto spec = [] {                                                                      using ::kota::meta::dsl::rename;                                                                   using ::kota::meta::dsl::description;                                                              using ::kota::meta::dsl::alias;                                                                    using ::kota::meta::dsl::idx;                                                                      using ::kota::meta::dsl::skip;                                                                     using ::kota::meta::dsl::flatten;                                                                  using ::kota::meta::dsl::defaulted;                                                                using ::kota::meta::dsl::skip_if;                                                                  using ::kota::meta::dsl::as;                                                                       using ::kota::meta::dsl::with;                                                                     using ::kota::meta::dsl::enum_string;                                                              using ::kota::meta::dsl::schema_default;                                                           using ::kota::meta::dsl::minimum;                                                                  using ::kota::meta::dsl::maximum;                                                                  using ::kota::meta::dsl::choices;                                                                  using ::kota::meta::dsl::rename_all;                                                               using ::kota::meta::dsl::deny_unknown_fields;                                                      using ::kota::meta::dsl::defaulted_fields;                                                         using ::kota::meta::dsl::tagged;                                                                   using ::kota::meta::dsl::tag;                                                                      using ::kota::meta::dsl::content;                                                                  using ::kota::meta::dsl::tag_names;                                                                using ::kota::meta::dsl::type;                                                                     using ::kota::meta::skip_when;                                                                     using ::kota::naming::Casing;                                                                      return ::kota::meta::make_annotation(__VA_ARGS__);                                             }();                                                                                           }
#define KOTATSU_ANNOTATE_IMPL(tag, ...)                                                                KOTATSU_ANNOTATION(tag, __VA_ARGS__);                                                              typename ::kota::meta::annotate<tag>::template type
#define KOTATSU_ANNOTATE(...)                                                                          KOTATSU_ANNOTATE_IMPL(KOTATSU_CONCAT(kotatsu_annotation_, __LINE__), __VA_ARGS__)
#define DECO_CONCAT_IMPL(a, b) a##b
#define DECO_CONCAT(a, b) DECO_CONCAT_IMPL(a, b)
#define DECO_OPTION_STRUCT_NAME(id) DECO_CONCAT(_DecoOptStruct_, id)
#define DECO_USING_OPTION_FIELDS                                                                       using _deco_base_t::required;                                                                      using _deco_base_t::category;
#define DECO_USING_CONFIG_COMMON                                                                       DECO_USING_OPTION_FIELDS                                                                           using _deco_base_t::help;                                                                          using _deco_base_t::meta_var;
#define DECO_USING_COMMON                                                                              DECO_USING_CONFIG_COMMON                                                                           using Step = typename _deco_callback_base_t::Step;                                                 using Action = typename _deco_callback_base_t::Action;                                             using _deco_callback_base_t::after_parsed;
#define DECO_USING_NAMED                                                                               DECO_USING_COMMON                                                                                  using _deco_base_t::names;
#define DECO_USING_FLAG DECO_USING_NAMED
#define DECO_USING_INPUT DECO_USING_COMMON
#define DECO_USING_KV                                                                                  DECO_USING_NAMED                                                                                   using _deco_base_t::style;
#define DECO_DECLARE_OPTION_TYPED_IMPL(id, option_base_ty, cfg_base_ty, using_block, ...)              struct DECO_OPTION_STRUCT_NAME(id) : public option_base_ty {                                           struct __deco_field_ty :                                                                               public kota::deco::decl::OptionDeclaration<cfg_base_ty,                                                                                       typename option_base_ty::result_type> {                 using_block constexpr __deco_field_ty() {                                                              __VA_ARGS__;                                                                                   }                                                                                              };                                                                                                 using _deco_base_t = option_base_ty;                                                               using _deco_base_t::_deco_base_t;                                                                  constexpr ~DECO_OPTION_STRUCT_NAME(id)() = default;                                            };                                                                                                 DECO_OPTION_STRUCT_NAME(id)
#define DECO_DECLARE_OPTION_TYPED(option_base_ty, cfg_base_ty, using_block, ...)                       DECO_DECLARE_OPTION_TYPED_IMPL(__LINE__, option_base_ty, cfg_base_ty, using_block, __VA_ARGS__)
#define DECO_DECLARE_OPTION_TEMPLATE_IMPL(id,                                                                                                res_concept,                                                                                       default_res_type,                                                                                  option_base_tpl,                                                                                   cfg_base_ty,                                                                                       using_block,                                                                                       ...)                                                         template <res_concept ResTy = default_res_type>                                                    struct DECO_OPTION_STRUCT_NAME(id) : public option_base_tpl<ResTy> {                                   struct __deco_field_ty : public kota::deco::decl::OptionDeclaration<cfg_base_ty, ResTy> {              using typename kota::deco::decl::OptionDeclaration<cfg_base_ty, ResTy>::_deco_base_t;              using typename kota::deco::decl::OptionDeclaration<cfg_base_ty,                                                                                       ResTy>::_deco_callback_base_t;                  using_block constexpr __deco_field_ty() {                                                              __VA_ARGS__;                                                                                   }                                                                                              };                                                                                                 constexpr static auto deco_field_ty = __deco_field_ty::deco_field_ty;                              using _deco_base_t = option_base_tpl<ResTy>;                                                       using _deco_base_t::_deco_base_t;                                                                  constexpr ~DECO_OPTION_STRUCT_NAME(id)() = default;                                            };                                                                                                 template <typename DefaultTy>                                                                      DECO_OPTION_STRUCT_NAME(id)(DefaultTy&&)                                                               ->DECO_OPTION_STRUCT_NAME(id)<std::remove_cvref_t<DefaultTy>>;                                 DECO_OPTION_STRUCT_NAME(id)
#define DECO_DECLARE_OPTION_TEMPLATE(res_concept,                                                                                       default_res_type,                                                                                  option_base_tpl,                                                                                   cfg_base_ty,                                                                                       using_block,                                                                                       ...)                                                              DECO_DECLARE_OPTION_TEMPLATE_IMPL(__LINE__,                                                                                          res_concept,                                                                                       default_res_type,                                                                                  option_base_tpl,                                                                                   cfg_base_ty,                                                                                       using_block,                                                                                       __VA_ARGS__)
#define DecoFlag(...)                                                                                  DECO_DECLARE_OPTION_TYPED(kota::deco::decl::FlagOption<bool>,                                                                kota::deco::decl::FlagFields,                                                                      DECO_USING_FLAG,                                                                                   __VA_ARGS__)
#define DecoInput(...)                                                                                 DECO_DECLARE_OPTION_TEMPLATE(kota::deco::trait::InputResultType,                                                                std::string,                                                                                       kota::deco::decl::InputOption,                                                                     kota::deco::decl::InputFields,                                                                     DECO_USING_INPUT,                                                                                  __VA_ARGS__)
#define DecoKVStyled(kv_style, ...)                                                                    DECO_DECLARE_OPTION_TEMPLATE(kota::deco::trait::ScalarResultType,                                                               std::string,                                                                                       kota::deco::decl::ScalarOption,                                                                    kota::deco::decl::KVFields,                                                                        DECO_USING_KV,                                                                                     style = kv_style;                                                                                  __VA_ARGS__)
#define DecoKV(...) DecoKVStyled(kota::deco::decl::KVStyle::Separate, __VA_ARGS__)
#define ZEST_SUITE(name, ...)                                                                          struct name##TEST;                                                                                 [[maybe_unused]] static const bool zest_registered_##name =                                            ::kota::zest::detail::keep_registered<name##TEST>();                                           struct name##TEST : __VA_OPT__(__VA_ARGS__, )::kota::zest::TestSuiteDef<name##TEST>
#define ZEST_MAKE_ATTRS(...)                                                                           [] constexpr {                                                                                         ::kota::zest::TestAttrs _a{};                                                                  [[maybe_unused]] auto& [skip, focus, serial, crashes] = _a;                                        __VA_ARGS__;                                                                                       return _a;                                                                                     }()
#define ZEST_CASE(name, ...)                                                                           inline static constexpr char _zest_file_##name[] = __FILE__;                                       virtual const void* _register_##name() {                                                               constexpr auto _zest_attrs_ = ZEST_MAKE_ATTRS(__VA_OPT__(__VA_ARGS__));                            return &_register_test_case<&Self::test_##name,                                                                                _zest_file_##name,                                                                                 __LINE__,                                                                                          _zest_attrs_>;                                                     }                                                                                                  void test_##name()
#define ZEST_SPLIT_BEGIN                                                                               _Pragma("clang diagnostic push")                                                                       _Pragma("clang diagnostic ignored \"-Woverloaded-shift-op-parentheses\"")
#define ZEST_SPLIT_END _Pragma("clang diagnostic pop")
#define ZEST_CHECK(checker, ...)                                                                       do {                                                                                                   ZEST_SPLIT_BEGIN                                                                                   ::kota::zest::detail::checker(::kota::zest::detail::Decomposer{} << __VA_ARGS__,                                                 #__VA_ARGS__);                                                       ZEST_SPLIT_END                                                                                 } while(0)
#define ZEXPECT(...) ZEST_CHECK(check, __VA_ARGS__)
#define ZASSERT(...) ZEST_CHECK(check_fatal, __VA_ARGS__)
