#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <sys/stat.h>
#include <time.h>
#include <emmintrin.h>
import std.compat;
#include "std.macros.h"
#include "libc.macros.h"

#include "spdlog/details/log_msg.h"
#include "spdlog/sinks/base_sink.h"
#include "spdlog/sinks/ringbuffer_sink.h"
#include "spdlog/spdlog.h"
