#include <fcntl.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <arm_neon.h>
import std.compat;
#include "std.macros.h"
#include "libc.macros.h"
import simdjson;
#include "simdjson.macros.h"
#define ROARING_EXCEPTIONS 0
#define ROARING_TERMINATE(message) std::abort()

#include "kota/async/async.h"
#include "kota/async/io/system.h"
#include "kota/codec/bincode/bincode.h"
#include "kota/codec/dyn/decode.h"
#include "kota/codec/dyn/dyn.h"
#include "kota/codec/fbs/fbs.h"
#include "kota/codec/json/json.h"
#include "kota/codec/json/schema.h"
#include "kota/codec/macro.h"
#include "kota/codec/toml/toml.h"
#include "kota/codec/visit/config.h"
#include "kota/deco/deco.h"
#include <kota/deco/option.h>
#include "kota/ipc/codec/bincode.h"
#include "kota/ipc/codec/json.h"
#include "kota/ipc/lsp/position.h"
#include "kota/ipc/lsp/progress.h"
#include "kota/ipc/lsp/protocol.h"
#include "kota/ipc/lsp/text.h"
#include "kota/ipc/lsp/uri.h"
#include "kota/ipc/peer.h"
#include "kota/ipc/protocol.h"
#include "kota/ipc/recording_transport.h"
#include "kota/ipc/transport.h"
#include "kota/meta/annotation.h"
#include "kota/meta/enum.h"
#include "kota/meta/repr.h"
#include "kota/meta/struct.h"
#include "kota/support/glob_pattern.h"
#include "kota/support/ranges.h"
#include "kota/zest/async.h"
#include "kota/zest/zest.h"
#include "roaring/roaring.hh"
