name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Submodules
        id: cache-submodules
        uses: actions/cache@v4
        with:
          path: |
            ./deps
            .git/modules/deps/
          key: submodules-${{ github.sha }}
          restore-keys: |
            submodules-
      
      - name: Update Submodules
        run: |
          git submodule init 
          git submodule update --recursive --depth 1

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.10

      - name: Install Clang 18
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O - https://apt.llvm.org/llvm.sh | sudo bash
          sudo apt-get install -y clang-18 llvm-18

      - name: Install GCC 14
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-14 g++-14 libstdc++-14-dev
  
      - name: Set GCC 14 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++

      - name: Check GCC version
        run: gcc --version
      - name: Install lld and ninja
        run: |
          sudo apt-get install -y lld ninja-build

      - name: Build
        run: |
          python3 ./scripts/build-llvm-dev.py
          bash ./scripts/build-dev-test.sh
          cmake --build build
          ./build/bin/clice-tests --test-dir=./tests

      











