name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Submodules
        id: cache-submodules
        uses: actions/cache@v4
        with:
          path: |
            ./deps
            .git/modules/deps/
          key: submodules-${{ github.sha }}
          restore-keys: |
            submodules-
      
      - name: Update Submodules
        run: |
          git submodule init 
          git submodule update --recursive --depth 1

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.10

      - name: Install clang
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -O - https://apt.llvm.org/llvm.sh | sudo bash
          sudo apt update
          sudo apt install -y clang-18 llvm-18
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/llvm llvm /usr/bin/llvm-18 100
          sudo update-alternatives --config clang
          sudo update-alternatives --config llvm

      - name: Install gcc
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-14 g++-14 libstdc++-14-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++
  
      - name: Build LLVM
        run: |
          python3 ./scripts/build-llvm-dev.py

      - name: Build clice
        run: |
          bash ./scripts/build-dev-test.sh
          cmake --build build
      
      - name: Run tests
        run: ./build/bin/clice-tests --test-dir=./tests
          

      











