name: deploy

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies in docus
        run: |
          cd docus
          npm install

      - name: Build docs
        run: |
          cd docus
          npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docus/.vitepress/dist
